apiVersion: v1
kind: PersistentVolume
metadata:
  name: oai-ran2
  labels:
    io.kompose.service: oai-ran-claim2
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: "/k8s-data/sharedpvgnb2/"
    server: 192.168.2.73
    
