apiVersion: v1
kind: PersistentVolume
metadata:
  name: oai-ran1
  labels:
    io.kompose.service: oai-ran1
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: "/home/oaikub2/sharedpvgnb1"
    
