apiVersion: v1
kind: PersistentVolume
metadata:
  name: upf-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/home/oaikub2/sharedpv3"
