apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnbsim1
  labels:
    app: gnbsim1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gnbsim1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gnbsim1
      annotations:
        k8s.v1.cni.cncf.io/networks: ue-net1
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: ue
        image: rohankharade/gnbsim:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 22100
          name: oai-gnbsim1
        - containerPort: 2152
          name: s1u
        - containerPort: 38412
          name: s1c
        - containerPort: 38422
          name: x2c
        - containerPort: 50000
          name: if5-ori
        - containerPort: 50001
          name: if5-ecpri
        - containerPort: 50002
          name: if4p5-c
        - containerPort: 50003
          name: if4p5-u
        env:
          - name: MCC
            value: "208"
          - name: MNC
            value: "95"
          - name: GNBID
            value: "1"
          - name: TAC
            value: "0xa000"
          - name: SST
            value: "222"
          - name: SD
            value: "123"
          - name: PagingDRX
            value: "v32"
          - name: RANUENGAPID
            value: "0"
          - name: IMEISV
            value: "35609204079514"
          - name: MSIN
            value: "0000000031"
          - name: RoutingIndicator
            value: "1234"
          - name: ProtectionScheme
            value: "null"
          - name: KEY
            value: "0C0A34601D4F07677303652C0462535B"
          - name: OPc
            value: "63bfa50ee6523365ff14c1f45f88737d"
          - name: DNN
            value: "default"
          - name: URL
            value: "http://www.asnt.org:8080/"
          - name: NRCellID
            value: "0"
          - name: USE_FQDN
            value: "no"
          - name: NGAPPeerAddr
            value: "192.168.18.177"
          - name: GTPuLocalAddr
            value: "192.168.18.131"
          - name: GTPuIFname
            value: "net1"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: gnbsim-sa1
      terminationGracePeriodSeconds: 30
