#{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  #name: {{ template "oai-spgwu-tiny.fullname" . }}
  name: {{ .Chart.Name }}-{{ .Values.namespace }}-pvc
  #name: upf-pvc
  namespace: 5gcn
#{{- with .Values.persistence.annotations  }}
#  annotations:
#{{ toYaml . | indent 4 }}
#{{- end }}
#  labels:
#    app: {{ template "oai-spgwu-tiny.fullname" . }}
#    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
#    release: "{{ .Release.Name }}"
#    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
#{{- if .Values.persistence.storageClass }}
#{{- if (eq "-" .Values.persistence.storageClass) }} 
  volumeName: upf-pv
  storageClassName: standard
#{{- else }}
#  storageClassName: "{{ .Values.persistence.storageClass }}"
#{{- end }}
#{{- end }}
#{{- end }}
