apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-dnn
  labels:
    app: oai-dnn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-dnn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oai-dnn
      annotations:
        k8s.v1.cni.cncf.io/networks: dnn-net1
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: dnn
        image: ubuntu:bionic
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: Always
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
