apiVersion: v1
kind: PersistentVolume
metadata:
  name: oai-ranu
  labels:
    io.kompose.service: oai-ranu
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: "/home/nsslm/sharedpvgnbu"
    
